spring:
  application:
    name: identity-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/identityDb}
    username: ${SPRING_DATASOURCE_USERNAME:identityUser}
    password: ${SPRING_DATASOURCE_PASSWORD:12345678}
  #    url: jdbc:postgresql://localhost:5434/identitydb
  #    username: identityUser
  #    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
#      defaultZone: http://localhost:8761/eureka/

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8081}
  realm: ${KEYCLOAK_REALM:ITS-realm}
  client-id: ${KEYCLOAK_CLIENT_ID:identity-service}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:KjaceHUSAVIKEh38ybI3kQ6RgMU5xnrF}
#  server-url: http://localhost:8081
#  realm: ITS-realm
#  client-id: identity-service
#  client-secret: KjaceHUSAVIKEh38ybI3kQ6RgMU5xnrF

server:
  port: ${SERVER_PORT:8082}
#  port: 8082

security:
  oauth2:
    resourceserver:
      jwt:
        #issuer-uri: http://localhost:8081/realms/ITS-realm
        issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/ITS-realm}
custom:
  datasource:
     host: ${DB_HOST:postgres_identity}
     port: ${DB_POST:5434}
     dbName: ${DB_NAME:identityDb}
     user: ${SPRING_DATASOURCE_USERNAME:identityUser}
     pass: ${SPRING_DATASOURCE_PASSWORD:12345678}
#    host: postgres_identity
#    port: 5434
#    dbName: identityDb
#    user: identityUser
#    pass: 12345678
