#server:
#  port: 8761
#
#spring:
#  security:
#    user:
#      name: eureka
#      password: 12345678
#  application:
#    name: eureka-server
#
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    enabled: true
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
