spring:
  application:
    name: user-profile-service
  datasource:
     url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/userProfileDb}
     username: ${SPRING_DATASOURCE_USERNAME:userProfileUser}
     password: ${SPRING_DATASOURCE_PASSWORD:12345678}
#    url: jdbc:postgresql://localhost:5435/userProfileDb
#    username: userProfileUser
#    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/ITS-realm}

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production-please-make-it-long-enough}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
#      defaultZone: http://localhost:8761/eureka/

server:
   port: ${SERVER_PORT:8083}
#  port: 8083

custom:
  datasource:
     host: ${DB_HOST:localhost}
     port: ${DB_PORT:5432}
     dbName: ${DB_NAME:userProfileDb}
     user: ${SPRING_DATASOURCE_USERNAME:userProfileUser}
     pass: ${SPRING_DATASOURCE_PASSWORD:12345678}
#    host: localhost
#    port: 5435
#    dbName: userProfileDb
#    user: userProfileUser
#    pass: 12345678

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
