spring:
  application:
    name: assessment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/assessmentDb}
    username: ${SPRING_DATASOURCE_USERNAME:assessmentUser}
    password: ${SPRING_DATASOURCE_PASSWORD:12345678}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/ITS-realm}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}

server:
  port: ${SERVER_PORT:8086}

custom:
  datasource:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    dbName: ${DB_NAME:assessmentDb}
    user: ${SPRING_DATASOURCE_USERNAME:assessmentUser}
    pass: ${SPRING_DATASOURCE_PASSWORD:12345678}
